import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer";
import "./globals.css";
import { Nunito } from "next/font/google";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "ReseaRead",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
      <div className="container">
        <NavigationBar />
        {children}    
      </div>
      <Footer/>
      </body>
    </html>
  );
}
